name: Lint
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pypa/hatch@install
      - name: Run ruff linter and formatter
        run: hatch fmt --check
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pypa/hatch@install
      - name: Run mypy
        run: hatch run types:check
